name: flutter_website
description: The flutter.dev website rebuilt in Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animations: ^1.0.0+5
  url_launcher: ^5.4.5
  video_player: ^0.10.9+1
  webview_flutter: ^0.3.20+2
  universal_html: ^1.2.2
  responsive_framework:
    path: responsive_framework/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/videos/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
          - asset: assets/fonts/roboto_regular.ttf
          - asset: assets/fonts/roboto_bold.ttf
            weight: 700
          - asset: assets/fonts/roboto_italic.ttf
            style: italic
