name: flutter_website
publish_to: none
description: The flutter.dev website rebuilt in Flutter.
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  animations: ^2.0.2
  url_launcher: ^6.0.20
  video_player: ^2.2.18
  webview_flutter: ^3.0.0
  universal_html: ^2.0.8
  google_fonts: ^2.3.1
  responsive_framework:
    path: responsive_framework/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
